image: robertcnelson/beagle-devscripts-kernel-debian-12-amd64
# https://git.beagleboard.org/beagleboard/ci-docker-images

cache:
  key: "$CI_PROJECT_NAME-ti-linux-rt-6.1.y"
  paths:
    - ccache.tar.gz

build:
  tags:
    - docker-amd64
  stage: build
  script:
    - mkdir -p /root/.cache/ccache/ || true
    - ccache -s
    - tar -xf ccache.tar.gz -C / || true
    - ccache -s
    - CORES=$(getconf _NPROCESSORS_ONLN)
    - make ARCH=arm CROSS_COMPILE=/usr/bin/arm-linux-gnueabihf- clean
    - make ARCH=arm CROSS_COMPILE=/usr/bin/arm-linux-gnueabihf- bb.org_defconfig
    - echo "make -j${CORES} ARCH=arm KBUILD_DEBARCH=armhf CROSS_COMPILE=/usr/bin/arm-linux-gnueabihf- LOCALVERSION=-ti-rt-r$CI_JOB_ID KDEB_SOURCENAME=linux-upstream KDEB_COMPRESS=xz bindeb-pkg"
    - make -j${CORES} ARCH=arm KBUILD_DEBARCH=armhf KDEB_PKGVERSION=1xross CROSS_COMPILE="ccache /usr/bin/arm-linux-gnueabihf-" LOCALVERSION=-ti-rt-r$CI_JOB_ID KDEB_SOURCENAME=linux-upstream KDEB_COMPRESS=xz bindeb-pkg
    - mv ../*.deb ./
    - ccache -s
    - tar -cf ccache.tar.gz /root/.cache/ccache/
  artifacts:
    expire_in: 28 days
    name: "$CI_PROJECT_NAME-$CI_JOB_ID"
    paths:
      - "linux-image-*.deb"
